### ISSUE TITLE
Asset Library URL is malformed

### ISSUE THREAD

**Issue by mathrick** [LuisEscorza/GodotLabelFontAutoSizer#3]
The download URL submitted to the Godot Asset Library is broken:
```
Error parsing URL: https://github.comhttps://github.com/LuisEscorza/GodotLabelFontAutoSizer/releases/download/v1.0.2_godot_4.2/GodotLabelFontAutoSizer-1.0.2_godot_4.2.zip.
```
i.e. the URL got pasted twice, in the middle of itself. Quick guess, are you using Linux and using middle-click paste for everything? I do, and that's a thing that happens pretty regularly to me :)

**Comment by LuisEscorza** [comment]
Damn, hadn't even noticed that after so long 🤦‍♂️... no Linux though, just general clumsiness; thank you for noticing and letting me know! I already submitted an edit with the correct URL 👍
