### ISSUE TITLE
I can't find right click to modify.

### ISSUE THREAD

**Issue by RakibRyan** [LuisEscorza/GodotLabelFontAutoSizer#4]
![Screenshot (60)](https://github.com/user-attachments/assets/c3223a5c-8fca-42e1-bb9f-fdf0f46322fd)

**Comment by LuisEscorza** [comment]
What are you trying to modify? I see the script is not yet attached, so that might be your issue. Read the instructions on the main page to see how it works 👀 (either drag and drop the script or right click -> change type, which I do see in your screenshot)

**Comment by RakibRyan** [comment]
you had written that I could convert preexisting rtf to this with left click. You didn't mention anything about attaching it to preexisting ones

**Comment by RakibRyan** [comment]
Oh nvm I'm just blind sometimes
