### ISSUE TITLE
Is this plugin compatible with Godot 4.3?

### ISSUE THREAD

**Issue by gabrieldevsouza** [LuisEscorza/GodotLabelFontAutoSizer#5]
I can't find anywhere explaining if this plugin is compatible with Godot 4.3 and I was not able to set up a LableAutoSizer. Not sure if I'm the one not understanding the instructions for setup or if the extension is just not compatible anymore.

**Comment by LuisEscorza** [comment]
Hi, I haven't had any time to test it yet for 4.3 and the last release is for 4.2.

**Comment by LuisEscorza** [comment]
Hi there, the addon was indeed working with 4.3, nevertheless, I just uploaded a new version, in case you want to try it. The way the addon works for the user is a bit different as well, so make sure to read the Readme.
