### ISSUE TITLE
Suggestion for optimization

### ISSUE THREAD

**Issue by BradB132** [LuisEscorza/GodotLabelFontAutoSizer#6]
Hi Luis,
Thanks for open sourcing your solution to this problem.

In both [rich_label_auto_sizer.gd](https://github.com/LuisEscorza/GodotLabelFontAutoSizer/blob/main/addons/label_font_auto_sizer/rich_label_auto_sizer.gd) and [label_auto_sizer.gd](https://github.com/LuisEscorza/GodotLabelFontAutoSizer/blob/main/addons/label_font_auto_sizer/label_auto_sizer.gd), the current approach is a linear one, where the size is incremented at a consistent interval. I can see the `_max_steps` variable was probably added to limit the computational cost of linearly scanning across all possible sizes. Instead you could do a binary search which would take the "time complexity" of this from linear O(n) to logarithmic O(log2(n)). This should fairly quickly converge on the correct value with less need to limit the number of iterations (which introduces the possibility of incorrect sizing).

**Comment by LuisEscorza** [comment]
Hi, the  `_max_steps` variable is not at all intended to control performance of the addon.. it's directly related to the `_size_per_step` variable and it's there just to declare a minimum size. Like, if the base font size is 8, the size per step is 2 and the max steps is 1, the font size will never be smaller than 6.

At the moment I'm updating the addon, reworking the whole thing so it's easier for the users, and the both he max steps and size per step variables won't be around anymore, just not for performance reasons though, as I don't think there is much left to do there given it's written in GDScript and Labels only offer so many ways to achieve what the addon tries to do.
